/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import static cafeteria.Productos.model;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Hugo J Esparza F
 */
public class Caja extends javax.swing.JPanel {

    Bebidas bebidas_panel = new Bebidas();
    Comidas comidas_panel = new Comidas();
    Postres postres_panel = new Postres();
    static DefaultTableModel model_caja;
    static DefaultTableModel model_ticket;

    public Caja() {
        initComponents();
        model_caja = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Producto", "Cant.", "Precio U.", "Sub-Total", "IVA", "Total"
                }
        ) {
            Class[] types = new Class[]{
                Object.class, Float.class, Float.class, Float.class, Float.class, Float.class
            };
            boolean[] canEdit = new boolean[]{
                false,false,false,false,false,false
            };


            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        
        model_ticket = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Producto", "Cant.",  "Importe"
                }
        ) {
            Class[] types = new Class[]{
                Object.class, Integer.class, Float.class
            };
            boolean[] canEdit = new boolean[]{
                false,false,false
            };


            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };


        caja_table.setModel(model_caja);
        detalleticket_table.setModel(model_ticket);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        facturado_panel = new javax.swing.JPanel();
        facturado_scrollpanel = new javax.swing.JScrollPane();
        caja_table = new javax.swing.JTable();
        base_label = new javax.swing.JLabel();
        base_textfield = new javax.swing.JTextField();
        iva_label = new javax.swing.JLabel();
        iva_textfield = new javax.swing.JTextField();
        total_label = new javax.swing.JLabel();
        total_caja_textfield = new javax.swing.JTextField();
        pagar_button1 = new javax.swing.JButton();
        pagar_button = new javax.swing.JButton();
        ticket_panel = new javax.swing.JPanel();
        nombrecomercial_label = new javax.swing.JLabel();
        direccion_label = new javax.swing.JLabel();
        cif_label = new javax.swing.JLabel();
        telf_label = new javax.swing.JLabel();
        nombre_label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fsimplificada_label = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        numerofs_label = new javax.swing.JLabel();
        numerofs_textfield = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        fechahora_textfield = new javax.swing.JTextField();
        atendido_label = new javax.swing.JLabel();
        camarero_textfield = new javax.swing.JTextField();
        mesa_label = new javax.swing.JLabel();
        num_mesa_textfield = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        cant_textfield = new javax.swing.JLabel();
        productos_label = new javax.swing.JLabel();
        importe_label = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        detalleticket_scrollpanel = new javax.swing.JScrollPane();
        detalleticket_table = new javax.swing.JTable();
        jSeparator7 = new javax.swing.JSeparator();
        baseticket_label = new javax.swing.JLabel();
        baseticket_textfield = new javax.swing.JTextField();
        ivaticket_textfield = new javax.swing.JTextField();
        ivaticket_label = new javax.swing.JLabel();
        totalticket_textfield = new javax.swing.JTextField();
        totalticket_label = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1440, 620));

        facturado_panel.setBackground(new java.awt.Color(255, 255, 255));
        facturado_panel.setForeground(new java.awt.Color(0, 0, 0));
        facturado_panel.setPreferredSize(new java.awt.Dimension(840, 560));

        facturado_scrollpanel.setBackground(new java.awt.Color(255, 255, 255));
        facturado_scrollpanel.setForeground(new java.awt.Color(255, 255, 255));
        facturado_scrollpanel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        facturado_scrollpanel.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        facturado_scrollpanel.setPreferredSize(new java.awt.Dimension(710, 560));

        caja_table.setBackground(new java.awt.Color(255, 255, 255));
        caja_table.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        caja_table.setForeground(new java.awt.Color(93, 125, 144));
        caja_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Producto", "Cant.", "Precio U. Neto", "Sub-Total", "I.V.A", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        caja_table.setColumnSelectionAllowed(true);
        caja_table.setGridColor(new java.awt.Color(93, 125, 144));
        caja_table.setSelectionBackground(new java.awt.Color(93, 125, 144));
        facturado_scrollpanel.setViewportView(caja_table);
        caja_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (caja_table.getColumnModel().getColumnCount() > 0) {
            caja_table.getColumnModel().getColumn(0).setResizable(false);
            caja_table.getColumnModel().getColumn(0).setPreferredWidth(33);
            caja_table.getColumnModel().getColumn(1).setResizable(false);
            caja_table.getColumnModel().getColumn(1).setPreferredWidth(192);
            caja_table.getColumnModel().getColumn(2).setResizable(false);
            caja_table.getColumnModel().getColumn(2).setPreferredWidth(100);
            caja_table.getColumnModel().getColumn(2).setHeaderValue("Precio U. Neto");
            caja_table.getColumnModel().getColumn(3).setResizable(false);
            caja_table.getColumnModel().getColumn(3).setPreferredWidth(100);
            caja_table.getColumnModel().getColumn(3).setHeaderValue("Sub-Total");
            caja_table.getColumnModel().getColumn(4).setResizable(false);
            caja_table.getColumnModel().getColumn(4).setPreferredWidth(100);
            caja_table.getColumnModel().getColumn(4).setHeaderValue("I.V.A");
            caja_table.getColumnModel().getColumn(5).setPreferredWidth(100);
            caja_table.getColumnModel().getColumn(5).setHeaderValue("Total");
        }

        base_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        base_label.setForeground(new java.awt.Color(0, 0, 0));
        base_label.setText("BASE IMPONIBLE:");

        base_textfield.setBackground(new java.awt.Color(255, 255, 255));
        base_textfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        base_textfield.setForeground(new java.awt.Color(93, 125, 144));
        base_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 125, 144), 2));
        base_textfield.setPreferredSize(new java.awt.Dimension(220, 30));
        base_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base_textfieldActionPerformed(evt);
            }
        });

        iva_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        iva_label.setForeground(new java.awt.Color(0, 0, 0));
        iva_label.setText("I.V.A:");

        iva_textfield.setBackground(new java.awt.Color(255, 255, 255));
        iva_textfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        iva_textfield.setForeground(new java.awt.Color(93, 125, 144));
        iva_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 125, 144), 2));
        iva_textfield.setPreferredSize(new java.awt.Dimension(220, 30));
        iva_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iva_textfieldActionPerformed(evt);
            }
        });

        total_label.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        total_label.setForeground(new java.awt.Color(0, 0, 0));
        total_label.setText("TOTAL:");

        total_caja_textfield.setBackground(new java.awt.Color(255, 255, 255));
        total_caja_textfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        total_caja_textfield.setForeground(new java.awt.Color(93, 125, 144));
        total_caja_textfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 125, 144), 2));
        total_caja_textfield.setPreferredSize(new java.awt.Dimension(220, 30));
        total_caja_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_caja_textfieldActionPerformed(evt);
            }
        });

        pagar_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/pagar.png"))); // NOI18N
        pagar_button1.setBorder(null);
        pagar_button1.setContentAreaFilled(false);
        pagar_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagar_button1ActionPerformed(evt);
            }
        });

        pagar_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/eliminarbpng.png"))); // NOI18N
        pagar_button.setBorder(null);
        pagar_button.setContentAreaFilled(false);
        pagar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout facturado_panelLayout = new javax.swing.GroupLayout(facturado_panel);
        facturado_panel.setLayout(facturado_panelLayout);
        facturado_panelLayout.setHorizontalGroup(
            facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturado_panelLayout.createSequentialGroup()
                .addGroup(facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facturado_scrollpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addGroup(facturado_panelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facturado_panelLayout.createSequentialGroup()
                                .addComponent(iva_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iva_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facturado_panelLayout.createSequentialGroup()
                                .addComponent(pagar_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(total_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_caja_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facturado_panelLayout.createSequentialGroup()
                                .addComponent(base_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(base_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(facturado_panelLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(pagar_button1)
                    .addContainerGap(458, Short.MAX_VALUE)))
        );
        facturado_panelLayout.setVerticalGroup(
            facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturado_panelLayout.createSequentialGroup()
                .addComponent(facturado_scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facturado_panelLayout.createSequentialGroup()
                        .addGroup(facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(base_label)
                            .addComponent(base_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iva_label)
                            .addComponent(iva_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total_label)
                            .addComponent(total_caja_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facturado_panelLayout.createSequentialGroup()
                        .addComponent(pagar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(facturado_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facturado_panelLayout.createSequentialGroup()
                    .addContainerGap(402, Short.MAX_VALUE)
                    .addComponent(pagar_button1)
                    .addGap(68, 68, 68)))
        );

        ticket_panel.setBackground(new java.awt.Color(255, 255, 255));
        ticket_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ticket_panel.setPreferredSize(new java.awt.Dimension(420, 540));

        nombrecomercial_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        nombrecomercial_label.setForeground(new java.awt.Color(0, 0, 0));
        nombrecomercial_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrecomercial_label.setText("Cafetería MCBOfeel");
        nombrecomercial_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        direccion_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        direccion_label.setForeground(new java.awt.Color(0, 0, 0));
        direccion_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        direccion_label.setText("C. de Serrano Galvache, 56, 28033 Madrid");
        direccion_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cif_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        cif_label.setForeground(new java.awt.Color(0, 0, 0));
        cif_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cif_label.setText("CIF: Y5842514E");
        cif_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        telf_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        telf_label.setForeground(new java.awt.Color(0, 0, 0));
        telf_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telf_label.setText("Telf: 675 38 54 66");
        telf_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nombre_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        nombre_label.setForeground(new java.awt.Color(0, 0, 0));
        nombre_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_label.setText("Hugo Jose Esparza Fanizzi");
        nombre_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setBackground(java.awt.Color.white);
        jSeparator1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 50));

        fsimplificada_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        fsimplificada_label.setForeground(new java.awt.Color(0, 0, 0));
        fsimplificada_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fsimplificada_label.setText("F.SIMPLIFICADA");
        fsimplificada_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator2.setBackground(java.awt.Color.white);
        jSeparator2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));

        numerofs_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        numerofs_label.setForeground(new java.awt.Color(0, 0, 0));
        numerofs_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numerofs_label.setText("Nro. Fact. simplificada:");
        numerofs_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        numerofs_textfield.setBackground(new java.awt.Color(255, 255, 255));
        numerofs_textfield.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        numerofs_textfield.setForeground(new java.awt.Color(0, 0, 0));
        numerofs_textfield.setText("001");
        numerofs_textfield.setBorder(null);
        numerofs_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerofs_textfieldActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(java.awt.Color.white);
        jSeparator3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));

        fechahora_textfield.setBackground(new java.awt.Color(255, 255, 255));
        fechahora_textfield.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        fechahora_textfield.setForeground(new java.awt.Color(0, 0, 0));
        fechahora_textfield.setText("10/06/2022 10:35");
        fechahora_textfield.setBorder(null);
        fechahora_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechahora_textfieldActionPerformed(evt);
            }
        });

        atendido_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        atendido_label.setForeground(new java.awt.Color(0, 0, 0));
        atendido_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        atendido_label.setText("Atendido por:");
        atendido_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        camarero_textfield.setBackground(new java.awt.Color(255, 255, 255));
        camarero_textfield.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        camarero_textfield.setForeground(new java.awt.Color(0, 0, 0));
        camarero_textfield.setText("Hugo");
        camarero_textfield.setBorder(null);
        camarero_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camarero_textfieldActionPerformed(evt);
            }
        });

        mesa_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        mesa_label.setForeground(new java.awt.Color(0, 0, 0));
        mesa_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mesa_label.setText("Mesa:");
        mesa_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        num_mesa_textfield.setBackground(new java.awt.Color(255, 255, 255));
        num_mesa_textfield.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        num_mesa_textfield.setForeground(new java.awt.Color(0, 0, 0));
        num_mesa_textfield.setText("001");
        num_mesa_textfield.setBorder(null);
        num_mesa_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_mesa_textfieldActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(java.awt.Color.white);
        jSeparator4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));

        jSeparator5.setBackground(java.awt.Color.white);
        jSeparator5.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));

        cant_textfield.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        cant_textfield.setForeground(new java.awt.Color(0, 0, 0));
        cant_textfield.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cant_textfield.setText("Cant.");
        cant_textfield.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        productos_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        productos_label.setForeground(new java.awt.Color(0, 0, 0));
        productos_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productos_label.setText("Productos");
        productos_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        importe_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        importe_label.setForeground(new java.awt.Color(0, 0, 0));
        importe_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        importe_label.setText("Importe");
        importe_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator6.setBackground(java.awt.Color.white);
        jSeparator6.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));

        detalleticket_scrollpanel.setBackground(new java.awt.Color(255, 255, 255));
        detalleticket_scrollpanel.setForeground(new java.awt.Color(255, 255, 255));
        detalleticket_scrollpanel.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        detalleticket_scrollpanel.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        detalleticket_scrollpanel.setPreferredSize(new java.awt.Dimension(710, 560));

        detalleticket_table.setBackground(new java.awt.Color(255, 255, 255));
        detalleticket_table.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        detalleticket_table.setForeground(new java.awt.Color(93, 125, 144));
        detalleticket_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cant.", "Productos", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detalleticket_table.setGridColor(new java.awt.Color(93, 125, 144));
        detalleticket_table.setSelectionBackground(new java.awt.Color(93, 125, 144));
        detalleticket_scrollpanel.setViewportView(detalleticket_table);
        detalleticket_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (detalleticket_table.getColumnModel().getColumnCount() > 0) {
            detalleticket_table.getColumnModel().getColumn(0).setResizable(false);
            detalleticket_table.getColumnModel().getColumn(0).setPreferredWidth(33);
            detalleticket_table.getColumnModel().getColumn(1).setResizable(false);
            detalleticket_table.getColumnModel().getColumn(1).setPreferredWidth(192);
            detalleticket_table.getColumnModel().getColumn(2).setResizable(false);
            detalleticket_table.getColumnModel().getColumn(2).setPreferredWidth(49);
        }

        jSeparator7.setBackground(java.awt.Color.white);
        jSeparator7.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));

        baseticket_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        baseticket_label.setForeground(new java.awt.Color(0, 0, 0));
        baseticket_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        baseticket_label.setText("Base:");
        baseticket_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        baseticket_textfield.setBackground(new java.awt.Color(255, 255, 255));
        baseticket_textfield.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        baseticket_textfield.setForeground(new java.awt.Color(0, 0, 0));
        baseticket_textfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        baseticket_textfield.setText("11,00€");
        baseticket_textfield.setBorder(null);
        baseticket_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseticket_textfieldActionPerformed(evt);
            }
        });

        ivaticket_textfield.setBackground(new java.awt.Color(255, 255, 255));
        ivaticket_textfield.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ivaticket_textfield.setForeground(new java.awt.Color(0, 0, 0));
        ivaticket_textfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ivaticket_textfield.setText("1,10€");
        ivaticket_textfield.setBorder(null);
        ivaticket_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivaticket_textfieldActionPerformed(evt);
            }
        });

        ivaticket_label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ivaticket_label.setForeground(new java.awt.Color(0, 0, 0));
        ivaticket_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ivaticket_label.setText("I.V.A:");
        ivaticket_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalticket_textfield.setBackground(new java.awt.Color(255, 255, 255));
        totalticket_textfield.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        totalticket_textfield.setForeground(new java.awt.Color(0, 0, 0));
        totalticket_textfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalticket_textfield.setText("12,10€");
        totalticket_textfield.setBorder(null);
        totalticket_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalticket_textfieldActionPerformed(evt);
            }
        });

        totalticket_label.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        totalticket_label.setForeground(new java.awt.Color(0, 0, 0));
        totalticket_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalticket_label.setText("TOTAL (Impuestos Incl.):");
        totalticket_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ticket_panelLayout = new javax.swing.GroupLayout(ticket_panel);
        ticket_panel.setLayout(ticket_panelLayout);
        ticket_panelLayout.setHorizontalGroup(
            ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombrecomercial_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(direccion_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cif_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(telf_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nombre_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fsimplificada_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addGroup(ticket_panelLayout.createSequentialGroup()
                .addComponent(cant_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productos_label, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(importe_label, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator6)
            .addComponent(detalleticket_scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(ticket_panelLayout.createSequentialGroup()
                .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticket_panelLayout.createSequentialGroup()
                        .addComponent(numerofs_label, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(numerofs_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(mesa_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(num_mesa_textfield))
                    .addGroup(ticket_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fechahora_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(atendido_label)
                        .addGap(4, 4, 4)
                        .addComponent(camarero_textfield))
                    .addGroup(ticket_panelLayout.createSequentialGroup()
                        .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalticket_label, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ivaticket_label, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baseticket_label, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ivaticket_textfield)
                            .addComponent(totalticket_textfield)
                            .addComponent(baseticket_textfield))))
                .addContainerGap())
            .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ticket_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator7)
                    .addContainerGap()))
        );
        ticket_panelLayout.setVerticalGroup(
            ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticket_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(nombrecomercial_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccion_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cif_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telf_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fsimplificada_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerofs_label)
                    .addComponent(numerofs_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa_label)
                    .addComponent(num_mesa_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechahora_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atendido_label)
                    .addComponent(camarero_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cant_textfield)
                    .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(productos_label)
                        .addComponent(importe_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detalleticket_scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseticket_label)
                    .addComponent(baseticket_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ivaticket_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ivaticket_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalticket_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalticket_label))
                .addContainerGap())
            .addGroup(ticket_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ticket_panelLayout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(facturado_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(ticket_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(facturado_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addComponent(ticket_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pagar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagar_buttonActionPerformed
        // TODO add your handling code here:
        borrarCaja();
        anularUltimoTicket();  
    }//GEN-LAST:event_pagar_buttonActionPerformed

    private void base_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_base_textfieldActionPerformed

    private void iva_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iva_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iva_textfieldActionPerformed

    private void total_caja_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_caja_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_caja_textfieldActionPerformed

    private void numerofs_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerofs_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerofs_textfieldActionPerformed

    private void fechahora_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechahora_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechahora_textfieldActionPerformed

    private void camarero_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camarero_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camarero_textfieldActionPerformed

    private void num_mesa_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_mesa_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_mesa_textfieldActionPerformed

    private void baseticket_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseticket_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseticket_textfieldActionPerformed

    private void ivaticket_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivaticket_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ivaticket_textfieldActionPerformed

    private void totalticket_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalticket_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalticket_textfieldActionPerformed

    private void pagar_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagar_button1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < Productos.cuenta_mesajtable.getRowCount(); i++) {
            for (int j = 0; j < caja_table.getRowCount(); j++) {
                if (String.valueOf(caja_table.getValueAt(j, 0)).equals(String.valueOf(Productos.cuenta_mesajtable.getValueAt(i, 0)))) {
                    Productos.cuenta_mesajtable.setValueAt((int) Productos.cuenta_mesajtable.getValueAt(i, 1) - (int) caja_table.getValueAt(j, 1), i, 1);
                }
                if ((int) Productos.cuenta_mesajtable.getValueAt(i, 1) == 0) {
                    Productos.model.removeRow(i);
                }
                
            }
        }
        Productos.total_textfield.setText(null);
        borrarCaja();
    }//GEN-LAST:event_pagar_button1ActionPerformed

    public void borrarCaja(){
        //borrar tablas
        for (int i = caja_table.getRowCount()-1; i >= 0 ; i--) {
            model_caja.removeRow(i);
            model_ticket.removeRow(i);
        }
        
        //textfield izquierda
        base_textfield.setText(null);
        iva_textfield.setText(null);
        total_caja_textfield.setText(null);
        
        //datos ticket
        baseticket_textfield.setText(null);
        ivaticket_textfield.setText(null);
        totalticket_textfield.setText(null);
        camarero_textfield.setText(null);
        num_mesa_textfield.setText(null);
        fechahora_textfield.setText(null);
        numerofs_textfield.setText(null);

        
        //Volver a detalle mesa
        MainFrame.caja_panel.setVisible(false);
        MainFrame.productos_panel.setVisible(true);
        
        Productos.quitarSeleccionProductos();
        Productos.total_seleccionado=0;
    }
    
    public void anularUltimoTicket(){
        //Cambiar registro como no pagado/ anulado
        String sql3 = "update detalle_ticket set Estado_ticket=0 where(id_ticket='" + Productos.ultimo_ticket + "')";
        Statement st3 = null;
        try {
            st3 = MainFrame.con.createStatement();//creamos un objeto sentencia SQL

            //puede devolver 0, -1 afecta a toda la tabla, n /registros aceptados para la actualizacion
            int n = st3.executeUpdate(sql3);
            if (n == 1) {
                System.out.println("Ticket Anulado");
            } else {
                System.out.println("Ticket no Anulado");
            }

        } catch (SQLException sqe) {
            System.out.println(sqe.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atendido_label;
    private javax.swing.JLabel base_label;
    protected static javax.swing.JTextField base_textfield;
    private javax.swing.JLabel baseticket_label;
    protected static javax.swing.JTextField baseticket_textfield;
    protected static javax.swing.JTable caja_table;
    protected static javax.swing.JTextField camarero_textfield;
    private javax.swing.JLabel cant_textfield;
    private javax.swing.JLabel cif_label;
    private javax.swing.JScrollPane detalleticket_scrollpanel;
    protected static javax.swing.JTable detalleticket_table;
    private javax.swing.JLabel direccion_label;
    private javax.swing.JPanel facturado_panel;
    private javax.swing.JScrollPane facturado_scrollpanel;
    protected static javax.swing.JTextField fechahora_textfield;
    private javax.swing.JLabel fsimplificada_label;
    private javax.swing.JLabel importe_label;
    private javax.swing.JLabel iva_label;
    protected static javax.swing.JTextField iva_textfield;
    private javax.swing.JLabel ivaticket_label;
    protected static javax.swing.JTextField ivaticket_textfield;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel mesa_label;
    private javax.swing.JLabel nombre_label;
    private javax.swing.JLabel nombrecomercial_label;
    protected static javax.swing.JTextField num_mesa_textfield;
    private javax.swing.JLabel numerofs_label;
    protected static javax.swing.JTextField numerofs_textfield;
    private javax.swing.JButton pagar_button;
    private javax.swing.JButton pagar_button1;
    private javax.swing.JLabel productos_label;
    private javax.swing.JLabel telf_label;
    private javax.swing.JPanel ticket_panel;
    protected static javax.swing.JTextField total_caja_textfield;
    private javax.swing.JLabel total_label;
    private javax.swing.JLabel totalticket_label;
    protected static javax.swing.JTextField totalticket_textfield;
    // End of variables declaration//GEN-END:variables
}
