/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import java.awt.*;
import java.sql.*;

/**
 *
 * @author Hugo J Esparza F
 */
public class Comidas extends javax.swing.JPanel {

    /**
     * Creates new form Bebidas
     */
    public Comidas() {
        initComponents();
        this.setLayout(new FlowLayout(FlowLayout.LEFT));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alas_pollo_button = new javax.swing.JButton();
        arepas_button = new javax.swing.JButton();
        bocatas_button = new javax.swing.JButton();
        churros_button = new javax.swing.JButton();
        croissant_button = new javax.swing.JButton();
        hamburguesa_button = new javax.swing.JButton();
        porras_button = new javax.swing.JButton();
        tostones_button = new javax.swing.JButton();
        tortilla_patatas_button = new javax.swing.JButton();
        tequeños_button = new javax.swing.JButton();
        sandwich_mixto_button = new javax.swing.JButton();
        patacon_button = new javax.swing.JButton();
        mermelada_button = new javax.swing.JButton();
        montadito_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(630, 460));
        setPreferredSize(new java.awt.Dimension(630, 460));

        alas_pollo_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        alas_pollo_button.setForeground(new java.awt.Color(0, 0, 0));
        alas_pollo_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/alitaspollob.png"))); // NOI18N
        alas_pollo_button.setText("ALAS POLLO");
        alas_pollo_button.setBorder(null);
        alas_pollo_button.setContentAreaFilled(false);
        alas_pollo_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alas_pollo_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alas_pollo_button.setPreferredSize(new java.awt.Dimension(100, 120));
        alas_pollo_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        alas_pollo_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alas_pollo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alas_pollo_buttonActionPerformed(evt);
            }
        });
        add(alas_pollo_button);

        arepas_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        arepas_button.setForeground(new java.awt.Color(0, 0, 0));
        arepas_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/arepab.png"))); // NOI18N
        arepas_button.setText("AREPAS");
        arepas_button.setBorder(null);
        arepas_button.setContentAreaFilled(false);
        arepas_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        arepas_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        arepas_button.setPreferredSize(new java.awt.Dimension(100, 120));
        arepas_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        arepas_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        arepas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arepas_buttonActionPerformed(evt);
            }
        });
        add(arepas_button);

        bocatas_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        bocatas_button.setForeground(new java.awt.Color(0, 0, 0));
        bocatas_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/bocatab.png"))); // NOI18N
        bocatas_button.setText("BOCATAS");
        bocatas_button.setBorder(null);
        bocatas_button.setContentAreaFilled(false);
        bocatas_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bocatas_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bocatas_button.setPreferredSize(new java.awt.Dimension(100, 120));
        bocatas_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bocatas_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bocatas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bocatas_buttonActionPerformed(evt);
            }
        });
        add(bocatas_button);

        churros_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        churros_button.setForeground(new java.awt.Color(0, 0, 0));
        churros_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/churrob.png"))); // NOI18N
        churros_button.setText("CHURROS");
        churros_button.setBorder(null);
        churros_button.setContentAreaFilled(false);
        churros_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        churros_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        churros_button.setPreferredSize(new java.awt.Dimension(100, 120));
        churros_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        churros_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        churros_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                churros_buttonActionPerformed(evt);
            }
        });
        add(churros_button);

        croissant_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        croissant_button.setForeground(new java.awt.Color(0, 0, 0));
        croissant_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/croasantb.png"))); // NOI18N
        croissant_button.setText("CROISSANT");
        croissant_button.setBorder(null);
        croissant_button.setContentAreaFilled(false);
        croissant_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        croissant_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        croissant_button.setPreferredSize(new java.awt.Dimension(100, 120));
        croissant_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        croissant_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        croissant_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croissant_buttonActionPerformed(evt);
            }
        });
        add(croissant_button);

        hamburguesa_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        hamburguesa_button.setForeground(new java.awt.Color(0, 0, 0));
        hamburguesa_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/hamburguesab.png"))); // NOI18N
        hamburguesa_button.setText("HAMBURGER");
        hamburguesa_button.setBorder(null);
        hamburguesa_button.setContentAreaFilled(false);
        hamburguesa_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hamburguesa_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hamburguesa_button.setPreferredSize(new java.awt.Dimension(100, 120));
        hamburguesa_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        hamburguesa_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        hamburguesa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburguesa_buttonActionPerformed(evt);
            }
        });
        add(hamburguesa_button);

        porras_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        porras_button.setForeground(new java.awt.Color(0, 0, 0));
        porras_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/porrab.png"))); // NOI18N
        porras_button.setText("PORRAS");
        porras_button.setBorder(null);
        porras_button.setContentAreaFilled(false);
        porras_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        porras_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        porras_button.setPreferredSize(new java.awt.Dimension(100, 120));
        porras_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        porras_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        porras_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porras_buttonActionPerformed(evt);
            }
        });
        add(porras_button);

        tostones_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        tostones_button.setForeground(new java.awt.Color(0, 0, 0));
        tostones_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/tostonesb.png"))); // NOI18N
        tostones_button.setText("TOSTONES");
        tostones_button.setBorder(null);
        tostones_button.setContentAreaFilled(false);
        tostones_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tostones_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tostones_button.setPreferredSize(new java.awt.Dimension(100, 120));
        tostones_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tostones_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tostones_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tostones_buttonActionPerformed(evt);
            }
        });
        add(tostones_button);

        tortilla_patatas_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        tortilla_patatas_button.setForeground(new java.awt.Color(0, 0, 0));
        tortilla_patatas_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/tortillapatatab.png"))); // NOI18N
        tortilla_patatas_button.setText("TORTILLA P");
        tortilla_patatas_button.setBorder(null);
        tortilla_patatas_button.setContentAreaFilled(false);
        tortilla_patatas_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tortilla_patatas_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tortilla_patatas_button.setPreferredSize(new java.awt.Dimension(100, 120));
        tortilla_patatas_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tortilla_patatas_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tortilla_patatas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tortilla_patatas_buttonActionPerformed(evt);
            }
        });
        add(tortilla_patatas_button);

        tequeños_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        tequeños_button.setForeground(new java.awt.Color(0, 0, 0));
        tequeños_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/tequeñosb.png"))); // NOI18N
        tequeños_button.setText("TEQUEÑOS");
        tequeños_button.setBorder(null);
        tequeños_button.setContentAreaFilled(false);
        tequeños_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tequeños_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tequeños_button.setPreferredSize(new java.awt.Dimension(100, 120));
        tequeños_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tequeños_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tequeños_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tequeños_buttonActionPerformed(evt);
            }
        });
        add(tequeños_button);

        sandwich_mixto_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        sandwich_mixto_button.setForeground(new java.awt.Color(0, 0, 0));
        sandwich_mixto_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/sandwich_mixtob.png"))); // NOI18N
        sandwich_mixto_button.setText("SANDWICH M");
        sandwich_mixto_button.setBorder(null);
        sandwich_mixto_button.setContentAreaFilled(false);
        sandwich_mixto_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sandwich_mixto_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sandwich_mixto_button.setPreferredSize(new java.awt.Dimension(100, 120));
        sandwich_mixto_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sandwich_mixto_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sandwich_mixto_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandwich_mixto_buttonActionPerformed(evt);
            }
        });
        add(sandwich_mixto_button);

        patacon_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        patacon_button.setForeground(new java.awt.Color(0, 0, 0));
        patacon_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/pataconb.png"))); // NOI18N
        patacon_button.setText("PATACÓN");
        patacon_button.setBorder(null);
        patacon_button.setContentAreaFilled(false);
        patacon_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        patacon_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        patacon_button.setPreferredSize(new java.awt.Dimension(100, 120));
        patacon_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        patacon_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patacon_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patacon_buttonActionPerformed(evt);
            }
        });
        add(patacon_button);

        mermelada_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        mermelada_button.setForeground(new java.awt.Color(0, 0, 0));
        mermelada_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/mermeladab.png"))); // NOI18N
        mermelada_button.setText("MERMELADA");
        mermelada_button.setBorder(null);
        mermelada_button.setContentAreaFilled(false);
        mermelada_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mermelada_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mermelada_button.setPreferredSize(new java.awt.Dimension(100, 120));
        mermelada_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mermelada_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mermelada_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mermelada_buttonActionPerformed(evt);
            }
        });
        add(mermelada_button);

        montadito_button.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        montadito_button.setForeground(new java.awt.Color(0, 0, 0));
        montadito_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/montaditob.png"))); // NOI18N
        montadito_button.setText("MONTADITO");
        montadito_button.setBorder(null);
        montadito_button.setContentAreaFilled(false);
        montadito_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        montadito_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        montadito_button.setPreferredSize(new java.awt.Dimension(100, 120));
        montadito_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        montadito_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        montadito_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montadito_buttonActionPerformed(evt);
            }
        });
        add(montadito_button);
    }// </editor-fold>//GEN-END:initComponents

    private void alas_pollo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alas_pollo_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("alitas_de_pollo");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_alas_pollo_buttonActionPerformed

    private void arepas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arepas_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("arepa");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_arepas_buttonActionPerformed

    private void bocatas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bocatas_buttonActionPerformed
        // TODO add your handling code here:
         try {
            Productos.agregarProducto("bocata");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_bocatas_buttonActionPerformed

    private void churros_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_churros_buttonActionPerformed
        // TODO add your handling code here:
         try {
            Productos.agregarProducto("churro");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_churros_buttonActionPerformed

    private void croissant_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croissant_buttonActionPerformed
        // TODO add your handling code here:
         try {
            Productos.agregarProducto("croissant");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_croissant_buttonActionPerformed

    private void hamburguesa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburguesa_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("hamburguesa");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_hamburguesa_buttonActionPerformed

    private void porras_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porras_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("porra");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_porras_buttonActionPerformed

    private void tostones_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tostones_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("tostones");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_tostones_buttonActionPerformed

    private void tortilla_patatas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tortilla_patatas_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("tortilla_de_patatas ");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_tortilla_patatas_buttonActionPerformed

    private void tequeños_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tequeños_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("tequeños");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_tequeños_buttonActionPerformed

    private void sandwich_mixto_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwich_mixto_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("sandwich_mixto");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_sandwich_mixto_buttonActionPerformed

    private void patacon_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patacon_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("patacon");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_patacon_buttonActionPerformed

    private void mermelada_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mermelada_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("mermelada");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_mermelada_buttonActionPerformed

    private void montadito_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montadito_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("montadito");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_montadito_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alas_pollo_button;
    private javax.swing.JButton arepas_button;
    private javax.swing.JButton bocatas_button;
    private javax.swing.JButton churros_button;
    private javax.swing.JButton croissant_button;
    private javax.swing.JButton hamburguesa_button;
    private javax.swing.JButton mermelada_button;
    private javax.swing.JButton montadito_button;
    private javax.swing.JButton patacon_button;
    private javax.swing.JButton porras_button;
    private javax.swing.JButton sandwich_mixto_button;
    private javax.swing.JButton tequeños_button;
    private javax.swing.JButton tortilla_patatas_button;
    private javax.swing.JButton tostones_button;
    // End of variables declaration//GEN-END:variables
}
