/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import java.sql.*;

/**
 *
 * @author Hugo J Esparza F
 */
public class Login extends javax.swing.JPanel {
    static String camarero_login;
    static String camarero_id;
    public Login() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user1_button = new javax.swing.JButton();
        user1_button1 = new javax.swing.JButton();
        user1_button2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(93, 125, 144));
        setPreferredSize(new java.awt.Dimension(1440, 620));

        user1_button.setBackground(new java.awt.Color(93, 125, 144));
        user1_button.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        user1_button.setForeground(new java.awt.Color(0, 0, 0));
        user1_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/luis.png"))); // NOI18N
        user1_button.setText("Luis");
        user1_button.setBorder(null);
        user1_button.setBorderPainted(false);
        user1_button.setContentAreaFilled(false);
        user1_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user1_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        user1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1_buttonActionPerformed(evt);
            }
        });

        user1_button1.setBackground(new java.awt.Color(93, 125, 144));
        user1_button1.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        user1_button1.setForeground(new java.awt.Color(0, 0, 0));
        user1_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/alicia.png"))); // NOI18N
        user1_button1.setText("Alicia");
        user1_button1.setBorder(null);
        user1_button1.setBorderPainted(false);
        user1_button1.setContentAreaFilled(false);
        user1_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user1_button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        user1_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1_button1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                user1_button1MousePressed(evt);
            }
        });
        user1_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1_button1ActionPerformed(evt);
            }
        });

        user1_button2.setBackground(new java.awt.Color(93, 125, 144));
        user1_button2.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        user1_button2.setForeground(new java.awt.Color(0, 0, 0));
        user1_button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/nico.png"))); // NOI18N
        user1_button2.setText("Nicolas");
        user1_button2.setBorder(null);
        user1_button2.setBorderPainted(false);
        user1_button2.setContentAreaFilled(false);
        user1_button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user1_button2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        user1_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(user1_button1)
                .addGap(100, 100, 100)
                .addComponent(user1_button2)
                .addGap(100, 100, 100)
                .addComponent(user1_button)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user1_button2)
                    .addComponent(user1_button)
                    .addComponent(user1_button1))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void user1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1_buttonActionPerformed

    private void user1_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1_button1ActionPerformed

    private void user1_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1_button2ActionPerformed

    private void user1_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1_button1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_user1_button1MouseClicked

    private void user1_button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1_button1MousePressed
        // TODO add your handling code here:
        camarero_login="Alicia";
        new Pinpad(null,true ).setVisible(true);
        
    }//GEN-LAST:event_user1_button1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton user1_button;
    private javax.swing.JButton user1_button1;
    private javax.swing.JButton user1_button2;
    // End of variables declaration//GEN-END:variables
}
