/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import java.awt.*;
import java.sql.*;


public class MainFrame extends javax.swing.JFrame {
    
    
    static Login login_panel= new Login();
    static Mesas mesas_panel= new Mesas();
    static Productos productos_panel = new Productos();
    static Caja caja_panel = new Caja();
    static Connection con;
    

    /**
     * Creates new form App/
     */
    public MainFrame() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foot_panel = new javax.swing.JPanel();
        feel_label = new javax.swing.JLabel();
        cafeteria_label = new javax.swing.JLabel();
        mcbo_label = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();
        pestaña_label = new javax.swing.JLabel();
        nav_panel = new javax.swing.JPanel();
        logout_button = new javax.swing.JButton();
        productos_button = new javax.swing.JButton();
        mesas_button = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(93, 125, 144));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        foot_panel.setBackground(new java.awt.Color(0, 0, 0));
        foot_panel.setForeground(new java.awt.Color(93, 125, 144));

        feel_label.setFont(new java.awt.Font("Arial", 1, 45)); // NOI18N
        feel_label.setForeground(new java.awt.Color(255, 255, 255));
        feel_label.setText("feel");
        feel_label.setPreferredSize(new java.awt.Dimension(452, 93));

        cafeteria_label.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        cafeteria_label.setForeground(new java.awt.Color(255, 255, 255));
        cafeteria_label.setText("CAFETERÍA");

        mcbo_label.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        mcbo_label.setForeground(new java.awt.Color(255, 255, 255));
        mcbo_label.setText("MCBO");

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/logo.png"))); // NOI18N

        pestaña_label.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        pestaña_label.setForeground(new java.awt.Color(255, 255, 255));
        pestaña_label.setText("LOGIN");

        javax.swing.GroupLayout foot_panelLayout = new javax.swing.GroupLayout(foot_panel);
        foot_panel.setLayout(foot_panelLayout);
        foot_panelLayout.setHorizontalGroup(
            foot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foot_panelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(mcbo_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feel_label, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(logo_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pestaña_label)
                .addGap(110, 110, 110))
            .addGroup(foot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(foot_panelLayout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(cafeteria_label)
                    .addContainerGap(886, Short.MAX_VALUE)))
        );
        foot_panelLayout.setVerticalGroup(
            foot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foot_panelLayout.createSequentialGroup()
                .addGroup(foot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(foot_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo_label))
                    .addGroup(foot_panelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(foot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mcbo_label)
                            .addComponent(feel_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(foot_panelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(pestaña_label)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(foot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(foot_panelLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(cafeteria_label)
                    .addContainerGap(85, Short.MAX_VALUE)))
        );

        nav_panel.setBackground(new java.awt.Color(93, 125, 144));

        logout_button.setBackground(new java.awt.Color(0, 0, 0));
        logout_button.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        logout_button.setForeground(new java.awt.Color(255, 255, 255));
        logout_button.setText("LOGOUT");
        logout_button.setBorder(null);
        logout_button.setPreferredSize(new java.awt.Dimension(270, 60));
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        productos_button.setBackground(new java.awt.Color(255, 255, 255));
        productos_button.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        productos_button.setForeground(new java.awt.Color(0, 0, 0));
        productos_button.setText("Productos");
        productos_button.setBorder(null);
        productos_button.setPreferredSize(new java.awt.Dimension(270, 60));
        productos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productos_buttonActionPerformed(evt);
            }
        });

        mesas_button.setBackground(new java.awt.Color(255, 255, 255));
        mesas_button.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        mesas_button.setForeground(new java.awt.Color(0, 0, 0));
        mesas_button.setText("Mesas");
        mesas_button.setBorder(null);
        mesas_button.setBorderPainted(false);
        mesas_button.setPreferredSize(new java.awt.Dimension(270, 60));
        mesas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesas_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nav_panelLayout = new javax.swing.GroupLayout(nav_panel);
        nav_panel.setLayout(nav_panelLayout);
        nav_panelLayout.setHorizontalGroup(
            nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(productos_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(mesas_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        nav_panelLayout.setVerticalGroup(
            nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productos_button, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(mesas_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        main_panel.setBackground(new java.awt.Color(93, 125, 144));
        main_panel.setPreferredSize(new java.awt.Dimension(1400, 620));
        main_panel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nav_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(foot_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1416, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(nav_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foot_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Color c = new Color(93,125,144);
        getContentPane().setBackground(c);
        //Paneles principales
        main_panel.add(login_panel);
        main_panel.add(productos_panel);
        main_panel.add(caja_panel);
        main_panel.add(mesas_panel);
        //Vista inicial Panel Login
        mesas_panel.setVisible(false);
        productos_panel.setVisible(false);
        caja_panel.setVisible(false);
        login_panel.setVisible(true);
        
        //Cargar driver MySQL
        try {
            MetodosReutilizables.CargarDriver.cargar("com.mysql.jdbc.Driver");
            System.out.println("Driver cargado correctamente");
        } catch (ClassNotFoundException cne) {
            System.out.println("Driver no cargado : "+cne.getMessage());
        }
        
        //Conectar a BD cafeteria
        try {
            con = MetodosReutilizables.ConectarDriver.conectar("jdbc:mysql://localhost/cafeteria", "root", "");
            System.out.println("Conectado correctamente a la BD");
        } catch (SQLException sqe) {
            System.out.println("No conectado a la BD: "+sqe.getMessage());
        }
        
       
    }//GEN-LAST:event_formWindowOpened

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
       
        mesas_panel.setVisible(false);
        productos_panel.setVisible(false);
        caja_panel.setVisible(false);
        login_panel.setVisible(true);
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void productos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productos_buttonActionPerformed
        // TODO add your handling code here:
        
        login_panel.setVisible(false);
        mesas_panel.setVisible(false);
        caja_panel.setVisible(false);
        productos_panel.setVisible(true);
        System.out.println("accediendo a producto");
        
    }//GEN-LAST:event_productos_buttonActionPerformed

    private void mesas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesas_buttonActionPerformed
        // TODO add your handling code here:
       
        login_panel.setVisible(false);
        productos_panel.setVisible(false);
        caja_panel.setVisible(false);
        mesas_panel.setVisible(true);
    }//GEN-LAST:event_mesas_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cafeteria_label;
    private javax.swing.JLabel feel_label;
    private javax.swing.JPanel foot_panel;
    private javax.swing.JLabel logo_label;
    private javax.swing.JButton logout_button;
    protected static javax.swing.JPanel main_panel;
    private javax.swing.JLabel mcbo_label;
    private javax.swing.JButton mesas_button;
    private javax.swing.JPanel nav_panel;
    private javax.swing.JLabel pestaña_label;
    private javax.swing.JButton productos_button;
    // End of variables declaration//GEN-END:variables
}
