/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

/**
 *
 * @author Hugo J Esparza F
 */
public class Mesas extends javax.swing.JPanel {

    static String numero_mesa;
    
    public Mesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesa1_button = new javax.swing.JButton();
        mesa2_button = new javax.swing.JButton();
        mesa3_button = new javax.swing.JButton();
        mesa4_button = new javax.swing.JButton();
        mesa5_button = new javax.swing.JButton();
        mesa6_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(93, 125, 144));
        setPreferredSize(new java.awt.Dimension(1440, 620));

        mesa1_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/mesa1.png"))); // NOI18N
        mesa1_button.setBorder(null);
        mesa1_button.setContentAreaFilled(false);
        mesa1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa1_buttonActionPerformed(evt);
            }
        });

        mesa2_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/mesa3.png"))); // NOI18N
        mesa2_button.setBorder(null);
        mesa2_button.setContentAreaFilled(false);
        mesa2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa2_buttonActionPerformed(evt);
            }
        });

        mesa3_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/mesa2.png"))); // NOI18N
        mesa3_button.setBorder(null);
        mesa3_button.setContentAreaFilled(false);
        mesa3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa3_buttonActionPerformed(evt);
            }
        });

        mesa4_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/mesa4.png"))); // NOI18N
        mesa4_button.setBorder(null);
        mesa4_button.setContentAreaFilled(false);
        mesa4_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa4_buttonActionPerformed(evt);
            }
        });

        mesa5_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/mesa6.png"))); // NOI18N
        mesa5_button.setBorder(null);
        mesa5_button.setContentAreaFilled(false);
        mesa5_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa5_buttonActionPerformed(evt);
            }
        });

        mesa6_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/mesa5.png"))); // NOI18N
        mesa6_button.setBorder(null);
        mesa6_button.setContentAreaFilled(false);
        mesa6_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa6_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mesa4_button)
                        .addGap(50, 50, 50)
                        .addComponent(mesa6_button)
                        .addGap(50, 50, 50)
                        .addComponent(mesa5_button))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mesa1_button)
                        .addGap(50, 50, 50)
                        .addComponent(mesa3_button)
                        .addGap(50, 50, 50)
                        .addComponent(mesa2_button)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesa3_button)
                    .addComponent(mesa2_button)
                    .addComponent(mesa1_button))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesa6_button)
                    .addComponent(mesa5_button)
                    .addComponent(mesa4_button))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mesa1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa1_buttonActionPerformed
        // TODO add your handling code here:
        seleccion_mesa("1");
    }//GEN-LAST:event_mesa1_buttonActionPerformed

    private void mesa2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa2_buttonActionPerformed
        // TODO add your handling code here:
         seleccion_mesa("2");
    }//GEN-LAST:event_mesa2_buttonActionPerformed

    private void mesa3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa3_buttonActionPerformed
        // TODO add your handling code here:
        seleccion_mesa("3");
    }//GEN-LAST:event_mesa3_buttonActionPerformed

    private void mesa4_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa4_buttonActionPerformed
        // TODO add your handling code here:
        seleccion_mesa("4");
    }//GEN-LAST:event_mesa4_buttonActionPerformed

    private void mesa5_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa5_buttonActionPerformed
        // TODO add your handling code here:
        seleccion_mesa("5");
    }//GEN-LAST:event_mesa5_buttonActionPerformed

    private void mesa6_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa6_buttonActionPerformed
        // TODO add your handling code here:
        seleccion_mesa("6");
    }//GEN-LAST:event_mesa6_buttonActionPerformed

    protected void seleccion_mesa(String num){
        numero_mesa=num;
        MainFrame.mesas_panel.setVisible(false);
        MainFrame.productos_panel.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mesa1_button;
    private javax.swing.JButton mesa2_button;
    private javax.swing.JButton mesa3_button;
    private javax.swing.JButton mesa4_button;
    private javax.swing.JButton mesa5_button;
    private javax.swing.JButton mesa6_button;
    // End of variables declaration//GEN-END:variables
}
