/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;


import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Hugo J Esparza F
 */
public class Pinpad extends javax.swing.JDialog {
       
    static String contraseña;
    
    
    public Pinpad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        contraseña="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_1 = new javax.swing.JButton();
        borrar_button = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        confirmar_button = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        password_field = new javax.swing.JPasswordField();
        button_4 = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        volver_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        button_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/1.png"))); // NOI18N
        button_1.setBorder(null);
        button_1.setContentAreaFilled(false);
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        borrar_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/borrar.png"))); // NOI18N
        borrar_button.setBorder(null);
        borrar_button.setContentAreaFilled(false);
        borrar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_buttonActionPerformed(evt);
            }
        });

        button_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/2.png"))); // NOI18N
        button_2.setBorder(null);
        button_2.setContentAreaFilled(false);
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        confirmar_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/confirmar.png"))); // NOI18N
        confirmar_button.setBorder(null);
        confirmar_button.setContentAreaFilled(false);
        confirmar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_buttonActionPerformed(evt);
            }
        });

        button_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/4.png"))); // NOI18N
        button_3.setBorder(null);
        button_3.setContentAreaFilled(false);
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/3.png"))); // NOI18N
        button_5.setBorder(null);
        button_5.setContentAreaFilled(false);
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        password_field.setEditable(false);
        password_field.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        password_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(93, 125, 144), 4, true));
        password_field.setPreferredSize(new java.awt.Dimension(350, 60));
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });

        button_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/6.png"))); // NOI18N
        button_4.setBorder(null);
        button_4.setContentAreaFilled(false);
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        button_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/0.png"))); // NOI18N
        button_0.setBorder(null);
        button_0.setContentAreaFilled(false);
        button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_0ActionPerformed(evt);
            }
        });

        button_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/7.png"))); // NOI18N
        button_6.setBorder(null);
        button_6.setContentAreaFilled(false);
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/9.png"))); // NOI18N
        button_7.setBorder(null);
        button_7.setContentAreaFilled(false);
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        button_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/8.png"))); // NOI18N
        button_8.setBorder(null);
        button_8.setContentAreaFilled(false);
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/5.png"))); // NOI18N
        button_9.setBorder(null);
        button_9.setContentAreaFilled(false);
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_9ActionPerformed(evt);
            }
        });

        volver_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/volver.png"))); // NOI18N
        volver_button.setBorder(null);
        volver_button.setContentAreaFilled(false);
        volver_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(borrar_button))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(button_9)
                                    .addComponent(button_0))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_2)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_4)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_6)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_8)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_7)
                                    .addComponent(button_3)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmar_button))))
                    .addComponent(volver_button))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrar_button)
                    .addComponent(confirmar_button)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_0)
                    .addComponent(button_1)
                    .addComponent(button_2)
                    .addComponent(button_5)
                    .addComponent(button_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_9)
                    .addComponent(button_4)
                    .addComponent(button_6)
                    .addComponent(button_8)
                    .addComponent(button_7))
                .addGap(36, 36, 36)
                .addComponent(volver_button)
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        // TODO add your handling code here:
        escribirPassword("1");
    }//GEN-LAST:event_button_1ActionPerformed

    private void borrar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_buttonActionPerformed
        // TODO add your handling code here:
        contraseña="";
        password_field.setText(contraseña);
    }//GEN-LAST:event_borrar_buttonActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        // TODO add your handling code here:
        escribirPassword("2");
    }//GEN-LAST:event_button_2ActionPerformed

    private void confirmar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_buttonActionPerformed
        // TODO add your handling code here:
        ResultSet rs = null;
        String sq12 = "select * from camareros where nombre='" + Login.camarero_login + "'";
        Statement st2 = null;

        try {
            st2 = MainFrame.con.createStatement();
            rs = st2.executeQuery(sq12);
            if (rs.next()) {
                System.out.println("Consulta realizada correctamente");
                
                if (contraseña.equals(rs.getString(3))) {
                    JOptionPane.showMessageDialog(null, "Credenciales correctas. Entrando en sistema");
                    Login.camarero_id=rs.getString(1);
                    MainFrame.mesas_panel.setVisible(true);
                    MainFrame.login_panel.setVisible(false);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales incorrectas. Intentelo nuevamente");
                    contraseña = "";
                    password_field.setText(contraseña);
                }
            } else {
                System.out.println("Consulta no realizada");
            }
        } catch (SQLException sqe) {
            System.out.println("Error al consultar BD: " + sqe.getMessage());
        }
    }//GEN-LAST:event_confirmar_buttonActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
        // TODO add your handling code here:
        escribirPassword("3");
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
        // TODO add your handling code here:
        escribirPassword("4");
    }//GEN-LAST:event_button_5ActionPerformed

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_password_fieldActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
        // TODO add your handling code here:
        escribirPassword("5");
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_0ActionPerformed
        // TODO add your handling code here:
        escribirPassword("0");
        
        
    }//GEN-LAST:event_button_0ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
        // TODO add your handling code here:
        escribirPassword("6");
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
        // TODO add your handling code here:
        escribirPassword("7");
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
        // TODO add your handling code here:
        escribirPassword("8");
    }//GEN-LAST:event_button_8ActionPerformed

    private void button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_9ActionPerformed
        // TODO add your handling code here:
        escribirPassword("9");
    }//GEN-LAST:event_button_9ActionPerformed

    private void volver_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_volver_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pinpad dialog = new Pinpad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    protected void escribirPassword(String tecla) {

        contraseña = contraseña + tecla;
        password_field.setText(contraseña);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar_button;
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton confirmar_button;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JButton volver_button;
    // End of variables declaration//GEN-END:variables
}
