/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import java.awt.FlowLayout;
import java.sql.*;

/**
 *
 * @author Hugo J Esparza F
 */
public class Postres extends javax.swing.JPanel {

    /**
     * Creates new form Bebidas
     */
    public Postres() {
        initComponents();
        this.setLayout(new FlowLayout(FlowLayout.LEFT));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tarta_chocolate_button = new javax.swing.JButton();
        tarta_zanahoria_button = new javax.swing.JButton();
        tarta_queso_button = new javax.swing.JButton();
        flan_button = new javax.swing.JButton();
        natilla_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(630, 460));
        setPreferredSize(new java.awt.Dimension(630, 460));

        tarta_chocolate_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tarta_chocolate_button.setForeground(new java.awt.Color(0, 0, 0));
        tarta_chocolate_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/tartachocolateb.png"))); // NOI18N
        tarta_chocolate_button.setText("T. CHOCO");
        tarta_chocolate_button.setBorder(null);
        tarta_chocolate_button.setContentAreaFilled(false);
        tarta_chocolate_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tarta_chocolate_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tarta_chocolate_button.setPreferredSize(new java.awt.Dimension(100, 120));
        tarta_chocolate_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tarta_chocolate_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tarta_chocolate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarta_chocolate_buttonActionPerformed(evt);
            }
        });
        add(tarta_chocolate_button);

        tarta_zanahoria_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tarta_zanahoria_button.setForeground(new java.awt.Color(0, 0, 0));
        tarta_zanahoria_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/tartazanahoriab.png"))); // NOI18N
        tarta_zanahoria_button.setText("T. ZANAHORIA");
        tarta_zanahoria_button.setBorder(null);
        tarta_zanahoria_button.setContentAreaFilled(false);
        tarta_zanahoria_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tarta_zanahoria_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tarta_zanahoria_button.setPreferredSize(new java.awt.Dimension(100, 120));
        tarta_zanahoria_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tarta_zanahoria_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tarta_zanahoria_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarta_zanahoria_buttonActionPerformed(evt);
            }
        });
        add(tarta_zanahoria_button);

        tarta_queso_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tarta_queso_button.setForeground(new java.awt.Color(0, 0, 0));
        tarta_queso_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/tartaquesob.png"))); // NOI18N
        tarta_queso_button.setText("T. QUESO");
        tarta_queso_button.setBorder(null);
        tarta_queso_button.setContentAreaFilled(false);
        tarta_queso_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tarta_queso_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tarta_queso_button.setPreferredSize(new java.awt.Dimension(100, 120));
        tarta_queso_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tarta_queso_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tarta_queso_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarta_queso_buttonActionPerformed(evt);
            }
        });
        add(tarta_queso_button);

        flan_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        flan_button.setForeground(new java.awt.Color(0, 0, 0));
        flan_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/flanb.png"))); // NOI18N
        flan_button.setText("FLAN");
        flan_button.setBorder(null);
        flan_button.setContentAreaFilled(false);
        flan_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        flan_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        flan_button.setPreferredSize(new java.awt.Dimension(100, 120));
        flan_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        flan_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        flan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flan_buttonActionPerformed(evt);
            }
        });
        add(flan_button);

        natilla_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        natilla_button.setForeground(new java.awt.Color(0, 0, 0));
        natilla_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/imagenes/natillab.png"))); // NOI18N
        natilla_button.setText("NATILLA");
        natilla_button.setBorder(null);
        natilla_button.setContentAreaFilled(false);
        natilla_button.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        natilla_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        natilla_button.setPreferredSize(new java.awt.Dimension(100, 120));
        natilla_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        natilla_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        natilla_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natilla_buttonActionPerformed(evt);
            }
        });
        add(natilla_button);
    }// </editor-fold>//GEN-END:initComponents

    private void tarta_chocolate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarta_chocolate_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("tarta_de_chocolate");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_tarta_chocolate_buttonActionPerformed

    private void tarta_zanahoria_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarta_zanahoria_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("tarta_de_zanahoria");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_tarta_zanahoria_buttonActionPerformed

    private void tarta_queso_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarta_queso_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("tarta_de_queso");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_tarta_queso_buttonActionPerformed

    private void flan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flan_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("flan");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_flan_buttonActionPerformed

    private void natilla_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natilla_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Productos.agregarProducto("natilla");
        } catch (SQLException sqe) {
            System.out.println("Consulta fallida:" + sqe.getMessage() + "");
        }
    }//GEN-LAST:event_natilla_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton flan_button;
    private javax.swing.JButton natilla_button;
    private javax.swing.JButton tarta_chocolate_button;
    private javax.swing.JButton tarta_queso_button;
    private javax.swing.JButton tarta_zanahoria_button;
    // End of variables declaration//GEN-END:variables
}
